CREATE TABLE TB_FILE
(
  IDX   NUMBER,
  ORIGINAL_FILE_NAME VARCHAR2(260 BYTE) NOT NULL,
  STORED_FILE_NAME VARCHAR2(36 BYTE) NOT NULL,
  FILE_SIZE NUMBER,
  CREA_DTM  DATE DEFAULT SYSDATE NOT NULL,
  DEL_GB    VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
  PRIMARY KEY (IDX)
);

CREATE SEQUENCE SEQ_TB_FILE_IDX
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCACHE;